# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiply a number by two
#'
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call(`_SMLN_timesTwo`, x)
}

prior_LN <- function(beta, sigma2, prior, logs) {
    .Call(`_SMLN_prior_LN`, beta, sigma2, prior, logs)
}

J_alpha <- function(alpha, k) {
    .Call(`_SMLN_J_alpha`, alpha, k)
}

II_alpha <- function(alpha) {
    .Call(`_SMLN_II_alpha`, alpha)
}

IIJ_nu <- function(nu) {
    .Call(`_SMLN_IIJ_nu`, nu)
}

r_GIG <- function(r, n = 1L) {
    .Call(`_SMLN_r_GIG`, r, n)
}

